### ISSUE TITLE
取り札70番の誤り

### ISSUE THREAD

**Issue by gentahgr** [pjmtdw/kazesomiso#1]
torifuda.txt 内70番下の句に誤りがあります．
いづくもおなじ あきのゆふぐれ → いづ**こ**もおなじ あきのゆふぐれ

以下を参照して確認しました
文英堂 原色小倉百人一首
大石天狗堂 標準百人一首　取札

yomifuda.txt は「いづこ」と正しく書かれていました．

**Comment by pjmtdw** [comment]
ありがとうございます．こちらの手持ちの札でも確認取れたので修正しました．
